name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"
      - name: Load & cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          node-version: '20'
      - run: npm ci --prefer-offline --no-audit --progress=false --ignore-scripts
      - run: npx nx format:check
      - run: pnpm exec nx affected -t lint test build
