name: Publish
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Run CI steps
        uses: ./.github/workflows/ci.yml@main
      - name: Set version
        run: npx nx release version minor
      - id: package
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"
      - name: Update changelog
        run: npx nx release changelog ${{ steps.package.outputs.version }}
      - name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - name: Publish
        run: npx nx release publish
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build(github): publish ${{ steps.package.outputs.version }} [skip ci]"
          tagging_message: "v${{ steps.package.outputs.version }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package.outputs.version }}
          release_name: Release ${{ steps.package.outputs.version }}
          draft: false
          prerelease: false