name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          node-version: '22'
      - run: npx nx format:check
      - run: npx nx run-many -t lint --max-parallel=4
      - run: npx nx run-many -t test --max-parallel=4
      - run: npx nx run-many -t build --max-parallel=4
